sudo: required
language: cpp
compiler: gcc

before_install:
  # codecov
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo pip install codecov # From https://github.com/travis-ci/travis-ci/issues/1705
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphviz

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - libboost1.55-all-dev

install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - ./install_oclint.sh

script: 
  # Build and run
  - qmake
  - make
  - ./Water-level-dynamics
  # Code coverage
  - ./get_code_cov.sh >/dev/null
  - codecov >/dev/null
  # OCLint
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
